name: production
on:
  push:
    branches:
      - production
jobs:
  build:
    runs-on: ["target-website-runner"]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: production
          submodules: false
      - name: Install deps
        run: npm ci
      - name: Build HTML
        run: npm run build
      - name: Push To Hostinger-Repo
        run: |
          git clone https://${{ secrets.HOSTINGER_REPO }} deploy-repo
          rm -rf deploy-repo/*
          cp -r dist/* deploy-repo/
          cd deploy-repo
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Deploy $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes"
          git push